# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CakePHP AdminLTE Theme
email: maiconsilva.pinto@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A CakePHP Theme based on AdminLTE Template. This theme was created thinking to facility the life of many developers that need to do aplications faster and better, like CakePHP filosofy. 
  Some steps and you already to start new elegant Panel. Join in group that use this simple and practical theme.
  The theme was installed more than 55K times.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: maiconpinto
github_username:  maiconpinto

# Build settings
markdown: kramdown
#theme: jekyll-theme-prettydocs
# for theme hosted on github
remote_theme: maiconpinto/jekyll-theme-prettydocs
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


branding_title: <span class="text-highlight">CakePHP</span><span class="text-bold">AdminLTE</span>
tagline_subtitle: >-
  A CakePHP Theme based on AdminLTE Template.
socials: true
github_repository: cakephp-adminlte-theme
download_url: https://github.com/maiconpinto/cakephp-adminlte-theme/archive/master.zip
card_components: false
card_charts: false
card_faqs: false
card_showcase: false
card_license: false